version: '3.8'
networks:
  network-cnginx-cwp:
    external: true
  network-cnginx-wp:
    external: true
  network-cwp-cdb:
    external: true
  network-wp:
    external: true
  network-db:
    external: true
volumes:
  wp-files:
    external: true
  db-data:
    external: true
