# docker-compose.yml
services:
  db:
    build:
      args:
        - BASE_IMAGE=inception/base:${APP_VERSION}
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: inception/mariadb:${APP_VERSION}
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - ${NETWORK}
    configs:
      - source: mariadb_config
        target: /etc/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "--password=${MYSQL_USER_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    env_file:
      - .env

  wordpress:
    build:
      args:
        - BASE_IMAGE=inception/base:${APP_VERSION}
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: inception/wordpress:${APP_VERSION}
    restart: always
    depends_on:
      - db
    volumes:
      - wp-files:/var/www/html
    networks:
      - ${NETWORK}
    healthcheck:
      test: ["CMD", "php", "-f", "/var/www/html/wordpress/wp-includes/version.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
    env_file:
      - .env

  nginx:
    build:
      args:
        - BASE_IMAGE=inception/base:${APP_VERSION}
        - DOMAIN_NAME="${DOMAIN_NAME}"
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: inception/nginx:${APP_VERSION}
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - db
    networks:
      - ${NETWORK}
    volumes:
      - wp-files:/var/www/html
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env

configs:
  nginx_config:
    file: ./requirements/nginx/conf/nginx.conf
  mariadb_config:
    file: ./requirements/mariadb/conf/my.cnf

networks:
  inception-network:
    driver: bridge

volumes:
  wp-files:
    driver: local
    driver_opts:
      type: none
      device: ${DIR_DATA_WP}
      o: bind
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ${DIR_DATA_DB}
      o: bind
