# docker-compose.yml
services:
  base:
    build:
      args:
        - OS=${OS}
        - OS_VERSION=${OS_VERSION}
      context: ./requirements/base
      dockerfile: Dockerfile
    image: inception/base:${APP_VERSION}

  db:
    build:
      args:
        - BASE_IMAGE=inception/base:${APP_VERSION}
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: inception/mariadb:${APP_VERSION}
    restart: always
    volumes:
      - ${VOLUME_DB}:/var/lib/mariadb
    networks:
      - ${NETWORK}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_ADMIN=${MYSQL_ADMIN}
      - MYSQL_ADMIN_PASSWORD=${MYSQL_ADMIN_PASSWORD}

  wordpress:
    build:
      args:
        - BASE_IMAGE=inception/base:${APP_VERSION}
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: inception/wordpress:${APP_VERSION}
    restart: always
    depends_on:
      - db
    volumes:
      - ${VOLUME_WP}:/usr/share/wordpress
    networks:
      - ${NETWORK}
    environment:
      - WP_ADMIN_USER=${MYSQL_ADMIN}
      - WP_ADMIN_PASSWORD=${MYSQL_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${MYSQL_ADMIN_EMAIL}
      - WP_DB_NAME=${MYSQL_DATABASE}
      - WP_USER=${MYSQL_USER}
      - WP_PASSWORD=${MYSQL_USER_PASSWORD}
      - WP_USER_EMAIL=${MYSQL_USER_EMAIL}

  nginx:
    build:
      args:
        - BASE_IMAGE=inception/base:${APP_VERSION}
        - DOMAIN_NAME="${DOMAIN_NAME}"
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: inception/nginx:${APP_VERSION}
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - ${VOLUME_WP}:/usr/share/wordpress
    networks:
      - ${NETWORK}
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
