# docker-compose.yml
version: '3.8'
services:
  base:
    build:
      args:
        - OS=${OS}
        - OS_VERSION=${OS_VERSION}
      context: .
      dockerfile: requirements/base/Dockerfile
    image: inception/base:latest
  
  db:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ${VOLUME_DB}:/var/lib/mariadb
    networks:
      - ${NETWORK_DB}
      - ${NETWORK_CWP_CDB}

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    restart: always
    ports:
      - "9001:9000"
    depends_on:
      - nginx
    volumes:
      - ${VOLUME_WP}:/usr/share/wordpress
    networks:
      - ${NETWORK_WP}

  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    image: inception/nginx:latest
    restart: always
    ports:
      - "443:443"
      - "9000:9000"
    depends_on:
      - base
    volumes:
      - ${VOLUME_WP}:/usr/share/wordpress
    networks:
      - ${NETWORK_CNGINX_CWP}
      - ${NETWORK_CNGINX_WP}
