# docker-compose.yml
services:
  base:
    build:
      args:
        - OS=${OS}
        - OS_VERSION=${OS_VERSION}
      context: ./requirements/base
      dockerfile: Dockerfile
    image: inception/base:${APP_VERSION}
    networks:
      - ${NETWORK}

  db:
    build:
      args:
        - BASE_IMAGE=inception/base:${APP_VERSION}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: inception/mariadb:${APP_VERSION}
    depends_on:
      - base
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - ${NETWORK}
    configs:
      - source: mariadb_config
        target: /etc/my.cnf
    healthcheck:
      test: [
        "CMD-SHELL",
        "mysqladmin ping -h localhost -u ${MYSQL_ADMIN} --password=\"$(cat /run/secrets/db_admin_password)\" || exit 1"
      ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    secrets:
      - db_root_password
      - db_admin_password
      - wp_admin_password
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_ADMIN_PASSWORD_FILE=/run/secrets/db_admin_password
      - WP_ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password

  wordpress:
    build:
      args:
        - BASE_IMAGE=inception/base:${APP_VERSION}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: inception/wordpress:${APP_VERSION}
    restart: always
    depends_on:
      - base
      - db
    volumes:
      - wp-files:/var/www/html
    networks:
      - ${NETWORK}
    healthcheck:
      test: ["CMD", "php", "-f", "/var/www/html/wp-includes/version.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
    env_file:
      - .env
    secrets:
      - wp_admin_password
      - wp_user_password
      - db_admin_password
    environment:
      - WP_ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password
      - WP_USER_PASSWORD_FILE=/run/secrets/wp_user_password
      - MYSQL_ADMIN_PASSWORD_FILE=/run/secrets/db_admin_password

  nginx:
    build:
      args:
        - BASE_IMAGE=inception/base:${APP_VERSION}
        - DOMAIN_NAME="${DOMAIN_NAME}"
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: inception/nginx:${APP_VERSION}
    restart: always
    ports:
      - "443:443"
    depends_on:
      - base
      - wordpress
      - db
    networks:
      - ${NETWORK}
    volumes:
      - wp-files:/var/www/html
    configs:
      - source: nginx_config_template
        target: /etc/nginx/nginx.conf.template
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env

configs:
  nginx_config_template:
    file: ./requirements/nginx/conf/nginx.conf.template
  mariadb_config:
    file: ./requirements/mariadb/conf/my.cnf

networks:
  inception_network:
    driver: bridge

volumes:
  wp-files:
    driver: local
    driver_opts:
      type: none
      device: ${DIR_DATA_WP}
      o: bind
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ${DIR_DATA_DB}
      o: bind
  
secrets:
  db_root_password:
    file: "${DIR_SECRET}/db_root_password"
  db_admin_password:
    file: "${DIR_SECRET}/db_admin_password"
  wp_admin_password:
    file: "${DIR_SECRET}/wp_admin_password"
  wp_user_password:
    file: "${DIR_SECRET}/wp_user_password"
